apps/Area/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
	url(r'^novedadesarea/(?P<pk>[0-9]+)/', views.NovedadesArea.as_view(), name='novedadesArea'),
	url(r'^eventosarea/(?P<pk>[0-9]+)/', views.EventosArea.as_view(), name='eventosArea'),
	url(r'^encuesta.area/(?P<pk>[0-9]+)/', views.EncuestaArea.as_view(), name='encuestaArea'),


]

apps/Encuesta/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^encuestas/', views.ListarEncuestas.as_view(), name='listarEncuestas'),
    url(r'^poll/(?P<pk>[0-9]+)/', views.Detalle_Encuesta.as_view(), name='detalle_encuesta'),
	url(r'^result/(?P<pk>[0-9]+)/', views.Resultado_Encuesta.as_view(), name='encuesta_result'),
	url(r'^vote/(?P<pk>[0-9]+)/', views.vote, name='ajax_vote'),
	url(r'^opcion/$', views.opcion, name='seleccionOpcion'),


]

apps/Novedad/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^novedades/', views.ListarNovedades.as_view(), name='listarNovedades'),
    url(r'^novedadesAnteriores/', views.ListarNovedadesViejas.as_view(), name='listarNovedadesViejas'),
    url(r'^detalleNoticia/(?P<pk>[0-9]+)/', views.Detalle_Novedad.as_view(), name='detalle_novedad'),
    url(r'^like-blog/$', views.like_count_blog, name='like_count_blog'),
    url(r'^Comentarios/Nuevo/(?P<pk>[0-9]+)/', views.Crear_Comentario, name='crear_comentario'),

]

apps/Sede/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
	url(r'^eventossede/(?P<pk>[0-9]+)/', views.EventosSede.as_view(), name='eventosSede'),
	url(r'^novedadessede/(?P<pk>[0-9]+)/', views.NovedadesSede.as_view(), name='novedadesSede'),

]

unitan/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from .views import Start, institucional
from apps.Novedad import views

from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^institucional/', institucional, name='institucional'),

    url(r'^$', views.ListarNovedades.as_view(), name='listarNovedades'),

    url(r'^Novedades/', view=include('apps.Novedad.urls', namespace='Novedad')),

    url(r'^Documentos/', view=include('apps.documentos.urls', namespace='Documento')),

    url(r'^Eventos/', view=include('apps.Evento.urls', namespace='Evento')),

    url(r'^Areas/', view=include('apps.Area.urls', namespace='Area')),

    url(r'^Sedes/', view=include('apps.Sede.urls', namespace='Sede')),

    url(r'^Encuestas/', view=include('apps.Encuesta.urls', namespace='Encuesta')),
    
    #url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Area/models.py
from django.db import models

# Create your models here.
class Area(models.Model):
    nombre = models.CharField(max_length=60,
                              verbose_name='nombre',
                              help_text='Nombre de la area')

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'area'
        verbose_name_plural = 'areas'

apps/Area/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from apps.usuarios.models import Usuario
from apps.core.decorators import group_required
from .models import Area
from apps.Novedad.models import Novedad
from apps.Evento.models import Evento
from apps.Sede.models import Sede
from apps.Encuesta.models import Encuesta
from django.core import serializers
from datetime import datetime, timedelta

import json


class NovedadesArea(ListView):
	model = Area
	paginate_by = 10
	template_name = "areas/novedadesArea.html"
	def get_context_data(self,**kwargs):
		context = super(NovedadesArea,self).get_context_data(**kwargs)
		context['area'] = Area.objects.get(id=self.kwargs['pk'])
		last_month = datetime.today() - timedelta(days=60)
		context['novedades'] = Novedad.objects.filter(area_id = self.kwargs['pk']).order_by('-fecha_creacion')
		context['sedes'] = Sede.objects.all()
		context['anteriores'] = Novedad.objects.filter(area_id = self.kwargs['pk']).exclude(fecha_creacion__gte=last_month).order_by('-fecha_creacion')[:10]
		paginator=context['paginator']
		pagActual=context['page_obj'].number
		cantPag=len(paginator.page_range)
		start=pagActual-2 if pagActual >= 2 else 0
		final= pagActual+2 if pagActual <= cantPag-2 else cantPag
		context['paginacion']=list(paginator.page_range)[start:final]
		context['areas'] = Area.objects.all()
		return context

class EventosArea(ListView):
	model = Area
	paginate_by = 10
	template_name = "areas/eventosArea.html"
	def get_context_data(self,**kwargs):
		context = super(EventosArea,self).get_context_data(**kwargs)
		context['area'] = Area.objects.get(id=self.kwargs['pk'])
		context['eventos'] = Evento.objects.filter(area_id = self.kwargs['pk']).order_by('-fecha_creacion')
		context['areas'] = Area.objects.all()
		context['sedes'] = Sede.objects.all()
		paginator=context['paginator']
		pagActual=context['page_obj'].number
		cantPag=len(paginator.page_range)
		start=pagActual-2 if pagActual >= 2 else 0
		final= pagActual+2 if pagActual <= cantPag-2 else cantPag
		context['paginacion']=list(paginator.page_range)[start:final]
		return context

class EncuestaArea(ListView):
	model = Area	
	template_name = 'areas/encuestasArea.html'
	paginate_by = 10
	def get_context_data(self,**kwargs):
		context = super(EncuestaArea,self).get_context_data(**kwargs)
		context['area'] = Area.objects.get(id=self.kwargs['pk'])
		context['encuestas'] = Encuesta.objects.filter(area_id = self.kwargs['pk'])
		context['areas'] = Area.objects.all()
		paginator=context['paginator']
		pagActual=context['page_obj'].number
		cantPag=len(paginator.page_range)
		start=pagActual-2 if pagActual >= 2 else 0
		final= pagActual+2 if pagActual <= cantPag-2 else cantPag
		context['paginacion']=list(paginator.page_range)[start:final]
		return context

templates/areas/encuestasArea.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}



<div class="page-header sm">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<!-- Page Header Wrapper -->
				<div class="page-header-wrapper">
					<!-- Title & Sub Title -->
					<h5 class="title">Encuestas</h5>
				</div><!-- Page Header Wrapper -->
			</div><!-- Coloumn -->
		</div><!-- Row -->
	</div><!-- Container -->
</div>
<div role="main" class="main">
	<div class="page-default bg-grey typo-dark">
		<!-- Container -->
		<div class="container">
			<div class="row">
				<!-- Page Content -->
				<div class="col-md-9">
					{% if encuestas %}
					<ul class="row" >
						{% for e in encuestas%}
						<li class="col-xs-12 blog-list-wrap" >
					<!-- Blog Wrapper -->
						<div class="row blog-wrap">
							<!-- Blog Detail Wrapper -->
							<div class="col-sm-12">
								<div class="blog-details">
									<h4>{{e.titulo}}</h4>
									<ul class="blog-meta" >
										<li><i class="fa fa-calendar-o"></i>{{e.fecha}}</li>
									</ul><!-- Blog Meta -->
									<p>{{e.pregunta}}</p>
									<a class="btn" href="{% url 'Encuesta:detalle_encuesta' e.id %}">Realizar encuesta</a>
								<a class="btn" href="{% url 'Encuesta:encuesta_result' e.id %}">Ver Resultados</a>
								</div><!-- Blog Detail Wrapper -->
							</div><!-- Blog Detail Column -->
						</div><!-- Blog Wrapper -->
					<!-- Divider -->
					<hr class="md">
				</li><!-- Column -->

						{%endfor%}
						{% include 'pagination/pagination.html' %}
					</ul><!-- Row -->
					{% else%}
					<div role="alert" class="alert alert-danger"> 
						<strong>No hay encuestas cargadas</strong> 
					</div>
					{%endif%}
				</div><!-- Column -->

				<div class="col-md-3">
					<!-- aside -->
					<aside class="sidebar">
						
						<!-- Widget -->
						<div class="widget">
							<h5 class="widget-title">Areas<span></span></h5>
							<ul class="go-widget">
								{% for a in areas %}
								<li><a href="{% url 'Area:encuestaArea' a.id %}">{{a.nombre}}<span class="badge"></span></a></li>
								{% endfor %}
							</ul>
						</div><!-- Widget -->
					</aside><!-- aside -->	
				</div><!-- Column -->
			</div><!-- Row -->	
		</div><!-- Container -->
	</div><!-- Page Default -->
</div><!-- Page Main -->

{% endblock content %}

{% block extra_js%}

<script type="text/javascript">

</script>

{% endblock extra_js%}

templates/areas/eventosArea.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}


<div class="page-header sm">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<!-- Page Header Wrapper -->
				<div class="page-header-wrapper">
					<!-- Title & Sub Title -->
					<h5 class="title">Eventos de {{area.nombre}}</h5>
				</div><!-- Page Header Wrapper -->
			</div><!-- Coloumn -->
		</div><!-- Row -->
	</div><!-- Container -->
</div>

<div role="main" class="main">
	<div class="page-default bg-grey typo-dark">
		<!-- Container -->
		<div class="container">
			<div class="row">
				<!-- Page Content -->
				<div class="col-md-9">
				{% if eventos %}
					<ul class="row">
				{% for e in eventos%}
				{% if e.imagen %}
                    <li class="col-xs-12 event-list-wrap">
					<!-- Blog Wrapper -->
						<div class="row event-wrap">
							<div class="col-sm-5">
                                        <div class="event-img-wrap">
									<img width="600" height="220" src="{{e.imagen.url}}" class="img-responsive" alt="Event">
									</div>
								<!-- Blog Image  Wrapper -->
							</div><!-- Blog Wrapper -->
							<!-- Blog Detail Wrapper -->
							<div class="col-sm-7">
									<div class="event-details">
										<h5><a href="event-single-left.html">{{e.titulo}}</a></h5>
										<ul class="events-meta">
											<li><i class="fa fa-calendar-o"></i>{{e.fecha}}</li>
											<li><i class="fa fa-map-marker"></i> {{e.sede.nombre}}</li>
										</ul><!-- Event Meta -->
										<p>{{e.descripcion}}</p>
									</div><!-- Event Meta -->
								</div>	<!-- Event details -->
						</div><!-- Blog Wrapper -->
					<!-- Divider -->
					<hr class="md">
				</li><!-- Column -->
				{% else%}
				<li class="col-xs-12 event-list-wrap">
					<!-- Blog Wrapper -->
						<div class="row event-wrap">
							<!-- Blog Detail Wrapper -->
							<div class="col-sm-12">
									<div class="event-details">
										<h5><a href="event-single-left.html">{{e.titulo}}</a></h5>
										<ul class="events-meta">
											<li><i class="fa fa-calendar-o"></i>{{e.fecha}}</li>
											<li><i class="fa fa-map-marker"></i> {{e.sede.nombre}}</li>
										</ul><!-- Event Meta -->
										<p>{{e.descripcion}}</p>
									</div><!-- Event Meta -->
								</div>	<!-- Event details -->
						</div><!-- Blog Wrapper -->
					<!-- Divider -->
					<hr class="md">
				</li><!-- Column -->
				{% endif %}
               {%endfor%}
               {% include 'pagination/pagination.html' %}
				
			</ul><!-- Row -->
			{% else%}
                        <div role="alert" class="alert alert-danger"> 
						<strong>No hay eventos cargados para este area</strong> 
					</div>
                    {%endif%}
		</div><!-- Column -->

		<div class="col-md-3">
					<!-- aside -->
					<aside class="sidebar">
						
						<!-- Widget -->
						<div class="widget">
							<h5 class="widget-title">Areas<span></span></h5>
							<ul class="go-widget">
								{% for a in areas %}
									<li><a href="{% url 'Area:eventosArea' a.id %}">{{a.nombre}}<span class="badge"></span></a></li>
								{% endfor %}
							</ul>
						</div><!-- Widget -->
					</aside><!-- aside -->	

					<aside class="sidebar">
						
						<!-- Widget -->
						<div class="widget">
							<h5 class="widget-title">Sedes<span></span></h5>
							<ul class="go-widget">
								{% for s in sedes %}
									<li><a href="{% url 'Sede:eventosSede' s.id %}">{{s.nombre}}<span class="badge"></span></a></li>
								{% endfor %}
							</ul>
						</div><!-- Widget -->
					</aside><!-- aside -->	
				</div><!-- Column -->
	</div><!-- Row -->	
		</div><!-- Container -->
	</div><!-- Page Default -->
</div><!-- Page Main -->

{% endblock content %}

templates/areas/novedadesArea.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}


<div class="page-header sm">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<!-- Page Header Wrapper -->
				<div class="page-header-wrapper">
					<!-- Title & Sub Title -->
					<h5 class="title">Novedades de {{area.nombre}}</h5>
				</div><!-- Page Header Wrapper -->
			</div><!-- Coloumn -->
		</div><!-- Row -->
	</div><!-- Container -->
</div>

<div role="main" class="main">
	<div class="page-default bg-grey typo-dark">
		<!-- Container -->
		<div class="container">
			<div class="row">
				<!-- Page Content -->
				<div class="col-md-9">
				{% if novedades %}
					<div class="grid" id="noticias" >
				{% for n in novedades%}
				{% if n.imagen_portada %}
                    <div class="grid-item" id="novedad{{n.pk}}">
							<!-- Blog Grid Wrapper -->
							<div class="blog-wrap">
								<!-- Blog Image Wrapper -->
								<div class="blog-img-wrap">
									<img src="{{n.imagen_portada.url}}" class="img-responsive" alt="Blog" width="600" height="220">
								</div><!-- Blog Wraper -->
								<!-- Blog Detail Wrapper -->
								<div class="blog-details">
									<h5>{{n.titulo}}</h5>
									<ul class="blog-meta">
										<li><i class="fa fa-calendar-o"></i>{{n.fecha_creacion}}</li>
										<li><a class="likes post-likes" id="{{n.pk}}" href="javascript: reload()"><i class="fa fa-thumbs-o-up"></i></a><span id="like-counter{{n.pk}}">{{n.likes}}</span></li>
									</ul><!-- Blog Meta -->
									<a class="btn" href="{% url 'Novedad:detalle_novedad' n.id %}">Leer mas</a>
								</div><!-- Blog Detail Wrapper -->
							</div><!-- Blog Wrapper -->
						</div>
				{% else%}
				<div class="grid-item" id="novedad{{n.pk}}">
							<!-- Blog Grid Wrapper -->
							<div class="blog-wrap">
								<!-- Blog Image Wrapper -->
								<!-- Blog Detail Wrapper -->
								<div class="blog-details">
									<h5><a href="blog-single-left.html">{{n.titulo}}</a></h5>
									<ul class="blog-meta">
										<li><i class="fa fa-calendar-o"></i>{{n.fecha_creacion}}</li>
										<li><a class="likes post-likes" id="{{n.pk}}" href="javascript: reload()"><i class="fa fa-thumbs-o-up"></i></a><span id="like-counter{{n.pk}}">{{n.likes}}</span></li>
									</ul><!-- Blog Meta -->
									<a class="btn" href="{% url 'Novedad:detalle_novedad' n.id %}">Leer mas</a>
								</div><!-- Blog Detail Wrapper -->
							</div><!-- Blog Wrapper -->
 				 </div>
				{% endif %}

               {%endfor%}
				
			</div><!-- Row -->
			{% else%}
                        <div role="alert" class="alert alert-danger"> 
						<strong>No hay novedades cargadas para este area</strong> 
					</div>
                    {%endif%}
		</div><!-- Column -->

		<div class="col-md-3">
					<!-- aside -->
					<aside class="sidebar">
						
						<!-- Widget -->
						<div class="widget">
							<h5 class="widget-title">Areas<span></span></h5>
							<ul class="go-widget">
								{% for a in areas %}
									<li><a href="{% url 'Area:novedadesArea' a.id %}">{{a.nombre}}<span class="badge"></span></a></li>
								{% endfor %}
							</ul>
						</div><!-- Widget -->
					</aside><!-- aside -->	

					<aside class="sidebar">
						
						<!-- Widget -->
						<div class="widget">
							<h5 class="widget-title">Sedes<span></span></h5>
							<ul class="go-widget">
								{% for s in sedes %}
									<li><a href="{% url 'Sede:novedadesSede' s.id %}">{{s.nombre}}<span class="badge"></span></a></li>
								{% endfor %}
							</ul>
						</div><!-- Widget -->

						<div class="widget">
							<h5 class="widget-title">Noticias Anteriores<span></span></h5>
							<ul class="thumbnail-widget">

								{% for a in anteriores %}
									<li>
									<div class="thumb-wrap">
									{% if a.imagen_portada %}
										<img alt="Thumb" class="img-responsive" src="{{a.imagen_portada.url}}" width="60" height="60">
									{% endif %}
									</div>
									<div class="thumb-content"><a href="{% url 'Novedad:detalle_novedad' a.id %}">{{a.titulo}}</a><span>{{a.fecha_creacion}}</span></div>	
									</li>
								{% endfor %}
								
							</ul><!-- Thumbnail Widget -->
						</div>


					</aside><!-- aside -->	
				</div><!-- Column -->
	</div><!-- Row -->	
		</div><!-- Container -->
	</div><!-- Page Default -->
</div><!-- Page Main -->

{% endblock content %}

{% block extra_js%}

<script type="text/javascript">

$('#noticias').on('click','.post-likes', function(){
        var id = $(this).attr("id");
        $.ajax({
                data:{'novedad_id':id},
                url : "{% url 'Novedad:like_count_blog' %}",
                type: 'get',
                cache: false,
                success: function(data){
                    $('#like-counter'+id).text(data);
                                         
                }
            });
      });
function reload(){
			var id = $(this).attr("id");
            var container = document.getElementById("like-counter"+id);
            var content = container.innerHTML;
            container.innerHTML= content;
        }



        $('.grid').masonry({
  // options
  itemSelector: '.grid-item',
  columnWidth: 200
});
</script>

{% endblock extra_js%}