apps/Area/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
	url(r'^novedadesarea/(?P<pk>[0-9]+)/', views.NovedadesArea.as_view(), name='novedadesArea'),
	url(r'^eventosarea/(?P<pk>[0-9]+)/', views.EventosArea.as_view(), name='eventosArea'),
	url(r'^encuesta.area/(?P<pk>[0-9]+)/', views.EncuestaArea.as_view(), name='encuestaArea'),


]

apps/Novedad/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^novedades/', views.ListarNovedades.as_view(), name='listarNovedades'),
    url(r'^novedadesAnteriores/', views.ListarNovedadesViejas.as_view(), name='listarNovedadesViejas'),
    url(r'^detalleNoticia/(?P<pk>[0-9]+)/', views.Detalle_Novedad.as_view(), name='detalle_novedad'),
    url(r'^like-blog/$', views.like_count_blog, name='like_count_blog'),
    url(r'^Comentarios/Nuevo/(?P<pk>[0-9]+)/', views.Crear_Comentario, name='crear_comentario'),

]

apps/Sede/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
	url(r'^eventossede/(?P<pk>[0-9]+)/', views.EventosSede.as_view(), name='eventosSede'),
	url(r'^novedadessede/(?P<pk>[0-9]+)/', views.NovedadesSede.as_view(), name='novedadesSede'),

]

unitan/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from .views import Start, institucional
from apps.Novedad import views

from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^institucional/', institucional, name='institucional'),

    url(r'^$', views.ListarNovedades.as_view(), name='listarNovedades'),

    url(r'^Novedades/', view=include('apps.Novedad.urls', namespace='Novedad')),

    url(r'^Documentos/', view=include('apps.documentos.urls', namespace='Documento')),

    url(r'^Eventos/', view=include('apps.Evento.urls', namespace='Evento')),

    url(r'^Areas/', view=include('apps.Area.urls', namespace='Area')),

    url(r'^Sedes/', view=include('apps.Sede.urls', namespace='Sede')),

    url(r'^Encuestas/', view=include('apps.Encuesta.urls', namespace='Encuesta')),
    
    #url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/novedades/detalleNoticia.html
{% extends "base.html" %}
{% load staticfiles %}
{% load tags %}
{% load embed_video_tags %}
{% block content %}
<div class="page-header sm">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<!-- Page Header Wrapper -->
				<div class="page-header-wrapper">
					<!-- Title & Sub Title -->
					<h5 class="title">Novedades</h5>
				</div><!-- Page Header Wrapper -->
			</div><!-- Coloumn -->
		</div><!-- Row -->
	</div><!-- Container -->
</div>
<div role="main" class="main">
	<div class="page-default bg-grey typo-dark">
		<!-- Container -->
		<div class="container">
			<div class="row">
				<!-- Page Content -->
				<div class="col-md-9">
					<div class="row">
						<!-- Blog Column -->
						<div class="col-xs-12 blog-single">
							<div class="blog-single-wrap">
								{% if object.imagen_portada %}
									
									{% if imagenes %}
									<div class="owl-carousel dots-inline" 
									data-animatein="" 
									data-animateout="" 
									data-items="1" data-margin="" 
									data-loop="true" 
									data-merge="true" 
									data-nav="true" 
									data-dots="true" 
									data-stagepadding="" 
									data-mobile="1" 
									data-tablet="1" 
									data-desktopsmall="2"  
									data-desktop="1" 
									data-autoplay="false" 
									data-delay="3000" 
									data-navigation="true">
									<div class="item">
										<img src="{{object.imagen_portada.url}}" height="500" width="800" >
									</div>
									{% for i in imagenes %}
									<div class="item">
										<img src="{{i.imagen.url}}" height="500" width="800" >
									</div>
									{% endfor%}
								</div><!-- carousel -->
								{% else%}
									<div class="blog-img-wrap">
									<img width="500" height="800" src="{{object.imagen_portada.url}}" class="img-responsive" alt="Event">
									</div>
									{% endif %}
                                {% endif %}
								<!-- Blog Detail Wrapper -->
								<div class="blog-single-details">
									<h4>{{object.titulo}}</h4>
									<ul class="blog-meta">
										<li><i class="fa fa-calendar-o"></i> {{object.fecha_creacion}}</li>
										<li><i class="fa fa-eye"></i> {{object.visitas}}</li>
										{% if object.area %}
										<li><i class="fa fa-folder"></i> {{object.area}}</li>
                                		{% endif %}
										
									</ul><!-- Blog Meta -->
									<!-- Blog Description -->
									<p>{{object.descripcion}}</p>
								</div><!-- Blog Detail Wrapper -->
							</div><!-- Blog Wrapper -->
							{% if object.url%}
							<div class="panel panel-default">
								<div class="panel-body">
									<h5>Ingresar a enlace:  <a target="_blank" href="{{object.url}}"><img src="{% static 'images/url.png'%}" height="40" width="40"></a>
									</h5>
								</div>
							</div>
							{% endif%}
							{% if object.pdf%}

							<div class="panel panel-default">
								<div class="panel-body">
									<h5>Ver archivo:  <a target="_blank" href="{{object.pdf.url}}"><img src="{% static 'images/pdf-page.png'%}" height="40" width="40"></a>
									</h5>
								</div>
							</div>
							{% endif%}
							{% if object.video%}
									<video width="400" controls>
									<source src="{{object.video.url}}" type="video/mp4">
									Este navegador no soporta este formato de video 
									</video>
							{% endif%}

							<div id="post-comment" class="post-block post-comments clearfix">
						<h4>Comentarios : </h4>
						<!-- Comments -->
						<ul class="comments" id="comment-collection">
						<li id="li-add">
							</li>
						{% if comentarios %}
						{% for c in comentarios %}
						
						<li id="comentario{{c.pk}}"> 
								<!-- Comment -->
								<div class="comment">
									<div class="comment-block">
										<div class="comment-arrow"></div>
										<span class="comment-by">
											<strong>{{c.nombre}}</strong>
										</span><!-- Comment By -->
										<p>{{c.mensaje}}</p>
										<span class="date pull-right">{{c.fecha}}</span>
									</div><!-- Comment Block -->
								</div><!-- Comment -->
							</li><!-- Comment -->

							<!-- Comment -->
							{% endfor %}
							
						
						{%else%}
							<div id="alert" role="alert" class="alert alert-danger"> 
								<strong>No hay comentarios</strong> 
							</div>
						{%endif%}
						</ul><!-- Comments Full -->
						<h4>Agregar un comentario : </h4>
						<form class="col s12" method="post" id="agregarCr" action="{% url 'Novedad:crear_comentario' object.pk %}">{% csrf_token %}
						<div class="row">
							<div class="col-sm-12">
								<div class="form-group">
									<input class="form-control" id="exampleInputName" placeholder="Nombre" type="text" name="nombre">
								</div>
								<div class="form-group textarea-message ">
									<textarea name="mensaje" class="textarea-message form-control" placeholder="Mensaje" rows="8"></textarea>
								</div>
								<button type="submit" value="Submit" class="btn">Comentar</button>
							</div><!-- Column -->
						</div><!-- Row -->
					</form>
					</div>
						</div><!-- Column -->
					</div><!-- Row -->
				</div><!-- Column -->
				<div class="col-md-3">
					<!-- aside -->
					<aside class="sidebar">
						
						<!-- Widget -->
						<div class="widget">
							<h5 class="widget-title">Areas<span></span></h5>
							<ul class="go-widget">
								{% for a in areas %}
									<li><a href="{% url 'Area:novedadesArea' a.id %}">{{a.nombre}}<span class="badge"></span></a></li>
								{% endfor %}
							</ul>
						</div><!-- Widget -->
					</aside><!-- aside -->	
					{% if object.pdf%}
					{% endif%}
				</div><!-- Column -->
			</div><!-- Row -->
		</div><!-- Container -->

	</div><!-- Page Default -->
</div><!-- Page Main -->
{% endblock content %}

{% block extra_js%}

<script type="text/javascript">

        $('#agregarCr').on('submit',function( event ){
       
        $.ajax({
                data: $(this).serialize(),
                url : $(this).attr('action'),
                type: 'POST',
                cache: false,


                success: function(data){
                	var d = (new Date()).toString().split(' ').splice(1,3).join(' ');

                   if (data == 'error'){
                    alert("Ooops Ocurrio un error al crear el comentario.");
                   }else{
                    salida = '<li id="comentario'+data.clave+'> <div class="comment">'
                    salida+= '<div class="comment-block"><div class="comment-arrow"></div><span class="comment-by"> <strong>'+data.nombre+'</strong> </span>'
                    salida += '<p>'+data.mensaje+'</p> <span class="date pull-right">'+d+'</span>'
                    salida += '</div>'
                    salida += '</div></li>'
                    
                    $('#alert').hide();
                    $('#comment-collection #li-add').before(salida);
                    $('#agregarCr')[0].reset();
                   }                                     
                }
            });
        return false;
      });

</script>

{% endblock extra_js%}


templates/novedades/listaNovedades.html
{% extends "base.html" %}
{% load staticfiles %}
{% load tags %}
{% load embed_video_tags %}
{% block content %}

<div class="page-header sm">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<!-- Page Header Wrapper -->
				<div class="page-header-wrapper">
					<!-- Title & Sub Title -->
					<h5 class="title">Novedades Generales {{count}}</h5>
				</div><!-- Page Header Wrapper -->
			</div><!-- Coloumn -->
		</div><!-- Row -->
	</div><!-- Container -->
</div>

<div role="main" class="main">
	<div class="page-default bg-grey typo-dark">
		<!-- Container -->
		<div class="container">
			<div class="row">
				<!-- Page Content -->
				<div class="col-md-9">
				{% if Novedad %}
					<div class="grid" id="noticias" >
				{% for n in Novedad%}
					{% if n.imagen_portada %}
					<div class="grid-item" id="novedad{{n.pk}}">
							<!-- Blog Grid Wrapper -->
							<div class="blog-wrap">
								<!-- Blog Image Wrapper -->
								<div class="blog-img-wrap">
									<img src="{{n.imagen_portada.url}}" class="img-responsive" alt="Blog" width="600" height="220">
								</div><!-- Blog Wraper -->
								<!-- Blog Detail Wrapper -->
								<div class="blog-details">
									<h5>{{n.titulo}}</h5>
									<ul class="blog-meta" >
										<li><i class="fa fa-calendar-o"></i>{{n.fecha_creacion}}</li>
										<li id="megusti{{n.pk}}"><a class="likes post-likes" id="{{n.pk}}" href="javascript: reload()"><i class="fa fa-thumbs-o-up"></i></a><span id="like-counter{{n.pk}}">{{n.likes}}</span></li>
									</ul><!-- Blog Meta -->
									<a class="btn" href="{% url 'Novedad:detalle_novedad' n.id %}">Leer mas</a>
								</div><!-- Blog Detail Wrapper -->
							</div><!-- Blog Wrapper -->
						</div>
				
				{% elif n.video %}
					<div class="grid-item" id="novedad{{n.pk}}">
							<!-- Blog Grid Wrapper -->
							<div class="blog-wrap">
								<!-- Blog Image Wrapper -->
								<div class="blog-img-wrap">
									<video width="100%" controls>
									<source src="{{n.video.url}}" type="video/mp4">
									Este navegador no soporta este formato de video 
									</video>
								</div><!-- Blog Wraper -->
								<!-- Blog Detail Wrapper -->
								<div class="blog-details">
									<h5>{{n.titulo}}</h5>
									<ul class="blog-meta">
										<li><i class="fa fa-calendar-o"></i>{{n.fecha_creacion}}</li>
										<li id="megusti{{n.pk}}"><a class="likes post-likes" id="{{n.pk}}" href="javascript: reload()"><i class="fa fa-thumbs-o-up"></i></a><span id="like-counter{{n.pk}}">{{n.likes}}</span></li>
									</ul><!-- Blog Meta -->
									<a class="btn" href="{% url 'Novedad:detalle_novedad' n.id %}">Leer mas</a>
								</div><!-- Blog Detail Wrapper -->
							</div><!-- Blog Wrapper -->
						</div>
				{% else%}
				<div class="grid-item" id="novedad{{n.pk}}">
							<!-- Blog Grid Wrapper -->
							<div class="blog-wrap">
								<!-- Blog Image Wrapper -->
								<!-- Blog Detail Wrapper -->
								<div class="blog-details">
									<h5>{{n.titulo}}</h5>
									<ul class="blog-meta">
										<li><i class="fa fa-calendar-o"></i>{{n.fecha_creacion}}</li>
										<li id="megusti{{n.pk}}"><a class="likes post-likes" id="{{n.pk}}" href="javascript: reload()"><i class="fa fa-thumbs-o-up"></i></a><span id="like-counter{{n.pk}}">{{n.likes}}</span></li>
									</ul><!-- Blog Meta -->
									<a class="btn" href="{% url 'Novedad:detalle_novedad' n.id %}">Leer mas</a>
								</div><!-- Blog Detail Wrapper -->
							</div><!-- Blog Wrapper -->
 				 </div>
				{% endif %}

               {%endfor%}

				
			</div><!-- Row -->

			<!--{% include 'pagination/pagination.html' %}-->

			{% else%}
                        <div role="alert" class="alert alert-danger"> 
						<strong>No hay novedades cargadas</strong> 
					</div>
                    {%endif%}
            <center><a class="btn" style="margin-top: 40px;" href="{% url 'Novedad:listarNovedadesViejas'%}">Ver Anteriores</a></center>


                    

		</div><!-- Column -->


		<div class="col-md-3">
					<!-- aside -->
					<aside class="sidebar">
						
						<!-- Widget -->
						<div class="widget">
							<h5 class="widget-title">Areas<span></span></h5>
							<ul class="go-widget">
								{% for a in areas %}
									<li><a href="{% url 'Area:novedadesArea' a.id %}">{{a.nombre}}<span class="badge"></span></a></li>
								{% endfor %}
							</ul>
						</div><!-- Widget -->
					</aside><!-- aside -->	

					<aside class="sidebar">
						
						<!-- Widget -->
						<div class="widget">
							<h5 class="widget-title">Sedes<span></span></h5>
							<ul class="go-widget">
								{% for s in sedes %}
									<li><a href="{% url 'Sede:novedadesSede' s.id %}">{{s.nombre}}<span class="badge"></span></a></li>
								{% endfor %}
							</ul>
						</div><!-- Widget -->

						<div class="widget">
							<h5 class="widget-title">Noticias Anteriores<span></span></h5>
							<ul class="thumbnail-widget">

								{% for a in anteriores %}
									<li>
									<div class="thumb-wrap">
									{% if a.imagen_portada %}
										<img alt="Thumb" class="img-responsive" src="{{a.imagen_portada.url}}" width="60" height="60">
									{% endif %}
									</div>
									<div class="thumb-content"><a href="{% url 'Novedad:detalle_novedad' a.id %}">{{a.titulo}}</a><span>{{a.fecha_creacion}}</span></div>	
									</li>
								{% endfor %}
								
							</ul><!-- Thumbnail Widget -->
						</div>
					</aside><!-- aside -->	
				</div><!-- Column -->
	</div><!-- Row -->	
		</div><!-- Container -->
	</div><!-- Page Default -->
</div><!-- Page Main -->

{% endblock content %}

{% block extra_js%}

<script type="text/javascript">

$('#noticias').on('click','.post-likes', function(){
        var id = $(this).attr("id");
        $.ajax({
                data:{'novedad_id':id},
                url : "{% url 'Novedad:like_count_blog' %}",
                type: 'get',
                cache: false,
                success: function(data){
                    $('#megusti'+id).html('<i class="fa fa-thumbs-o-up"></i><span id="like-counter{{n.pk}}">'+data+'</span>');
                                         
                }
            });
      });

		function reload(){
			var id = $(this).attr("id");            
			var container = document.getElementById("like-counter"+id);
            var content = container.innerHTML;
            container.innerHTML= content;
        }



        $('.grid').masonry({
  // options
  itemSelector: '.grid-item',
  columnWidth: 200
});
</script>

{% endblock extra_js%}

templates/novedades/listaNovedadesViejas.html
{% extends "base.html" %}
{% load staticfiles %}
{% load tags %}
{% load embed_video_tags %}
{% block content %}

<div class="page-header sm">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<!-- Page Header Wrapper -->
				<div class="page-header-wrapper">
					<!-- Title & Sub Title -->
					<h5 class="title">Novedades Generales {{count}}</h5>
				</div><!-- Page Header Wrapper -->
			</div><!-- Coloumn -->
		</div><!-- Row -->
	</div><!-- Container -->
</div>

<div role="main" class="main">
	<div class="page-default bg-grey typo-dark">
		<!-- Container -->
		<div class="container">
			<div class="row">
				<!-- Page Content -->
				<div class="col-md-9">
				{% if Novedad %}
					<div class="grid" id="noticias" >
				{% for n in Novedad%}
					{% if n.imagen_portada %}
					<div class="grid-item" id="novedad{{n.pk}}">
							<!-- Blog Grid Wrapper -->
							<div class="blog-wrap">
								<!-- Blog Image Wrapper -->
								<div class="blog-img-wrap">
									<img src="{{n.imagen_portada.url}}" class="img-responsive" alt="Blog" width="600" height="220">
								</div><!-- Blog Wraper -->
								<!-- Blog Detail Wrapper -->
								<div class="blog-details">
									<h5>{{n.titulo}}</h5>
									<ul class="blog-meta">
										<li><i class="fa fa-calendar-o"></i>{{n.fecha_creacion}}</li>
										<li><a class="likes post-likes" id="{{n.pk}}" href="javascript: reload()"><i class="fa fa-thumbs-o-up"></i></a><span id="like-counter{{n.pk}}">{{n.likes}}</span></li>
									</ul><!-- Blog Meta -->
									<a class="btn" href="{% url 'Novedad:detalle_novedad' n.id %}">Leer mas</a>
								</div><!-- Blog Detail Wrapper -->
							</div><!-- Blog Wrapper -->
						</div>
				
				{% elif n.video %}
					<div class="grid-item" id="novedad{{n.pk}}">
							<!-- Blog Grid Wrapper -->
							<div class="blog-wrap">
								<!-- Blog Image Wrapper -->
								<div class="blog-img-wrap">
									<video width="100%" controls>
									<source src="{{n.video.url}}" type="video/mp4">
									Este navegador no soporta este formato de video 
									</video>
								</div><!-- Blog Wraper -->
								<!-- Blog Detail Wrapper -->
								<div class="blog-details">
									<h5>{{n.titulo}}</h5>
									<ul class="blog-meta">
										<li><i class="fa fa-calendar-o"></i>{{n.fecha_creacion}}</li>
										<li><a class="likes post-likes" id="{{n.pk}}" href="javascript: reload()"><i class="fa fa-thumbs-o-up"></i></a><span id="like-counter{{n.pk}}">{{n.likes}}</span></li>
									</ul><!-- Blog Meta -->
									<a class="btn" href="{% url 'Novedad:detalle_novedad' n.id %}">Leer mas</a>
								</div><!-- Blog Detail Wrapper -->
							</div><!-- Blog Wrapper -->
						</div>
				{% else%}
				<div class="grid-item" id="novedad{{n.pk}}">
							<!-- Blog Grid Wrapper -->
							<div class="blog-wrap">
								<!-- Blog Image Wrapper -->
								<!-- Blog Detail Wrapper -->
								<div class="blog-details">
									<h5>{{n.titulo}}</h5>
									<ul class="blog-meta">
										<li><i class="fa fa-calendar-o"></i>{{n.fecha_creacion}}</li>
										<li><a class="likes post-likes" id="{{n.pk}}" href="javascript: reload()"><i class="fa fa-thumbs-o-up"></i></a><span id="like-counter{{n.pk}}">{{n.likes}}</span></li>
									</ul><!-- Blog Meta -->
									<a class="btn" href="{% url 'Novedad:detalle_novedad' n.id %}">Leer mas</a>
								</div><!-- Blog Detail Wrapper -->
							</div><!-- Blog Wrapper -->
 				 </div>
				{% endif %}

               {%endfor%}
				
			</div><!-- Row -->
			{% include 'pagination/pagination.html' %}
			{% else%}
                        <div role="alert" class="alert alert-danger"> 
						<strong>No hay novedades cargadas</strong> 
					</div>
                    {%endif%}


                    

		</div><!-- Column -->

		<div class="col-md-3">
					<!-- aside -->
					<aside class="sidebar">
						
						<!-- Widget -->
						<div class="widget">
							<h5 class="widget-title">Areas<span></span></h5>
							<ul class="go-widget">
								{% for a in areas %}
									<li><a href="{% url 'Area:novedadesArea' a.id %}">{{a.nombre}}<span class="badge"></span></a></li>
								{% endfor %}
							</ul>
						</div><!-- Widget -->
					</aside><!-- aside -->	

					<aside class="sidebar">
						
						<!-- Widget -->
						<div class="widget">
							<h5 class="widget-title">Sedes<span></span></h5>
							<ul class="go-widget">
								{% for s in sedes %}
									<li><a href="{% url 'Sede:novedadesSede' s.id %}">{{s.nombre}}<span class="badge"></span></a></li>
								{% endfor %}
							</ul>
						</div><!-- Widget -->
					</aside><!-- aside -->	
				</div><!-- Column -->
	</div><!-- Row -->	
		</div><!-- Container -->
	</div><!-- Page Default -->
</div><!-- Page Main -->

{% endblock content %}

{% block extra_js%}

<script type="text/javascript">

$('#noticias').on('click','.post-likes', function(){
        var id = $(this).attr("id");
        $.ajax({
                data:{'novedad_id':id},
                url : "{% url 'Novedad:like_count_blog' %}",
                type: 'get',
                cache: false,
                success: function(data){
                    $('#like-counter'+id).text(data);
                                         
                }
            });
      });
function reload(){
			var id = $(this).attr("id");
            var container = document.getElementById("like-counter"+id);
            var content = container.innerHTML;
            container.innerHTML= content;
        }



        $('.grid').masonry({
  // options
  itemSelector: '.grid-item',
  columnWidth: 200
});
</script>

{% endblock extra_js%}