apps/Area/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
	url(r'^novedadesarea/(?P<pk>[0-9]+)/', views.NovedadesArea.as_view(), name='novedadesArea'),
	url(r'^eventosarea/(?P<pk>[0-9]+)/', views.EventosArea.as_view(), name='eventosArea'),
	url(r'^encuesta.area/(?P<pk>[0-9]+)/', views.EncuestaArea.as_view(), name='encuestaArea'),


]

apps/Encuesta/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^encuestas/', views.ListarEncuestas.as_view(), name='listarEncuestas'),
    url(r'^poll/(?P<pk>[0-9]+)/', views.Detalle_Encuesta.as_view(), name='detalle_encuesta'),
	url(r'^result/(?P<pk>[0-9]+)/', views.Resultado_Encuesta.as_view(), name='encuesta_result'),
	url(r'^vote/(?P<pk>[0-9]+)/', views.vote, name='ajax_vote'),
	url(r'^opcion/$', views.opcion, name='seleccionOpcion'),


]

unitan/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from .views import Start, institucional
from apps.Novedad import views

from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^institucional/', institucional, name='institucional'),

    url(r'^$', views.ListarNovedades.as_view(), name='listarNovedades'),

    url(r'^Novedades/', view=include('apps.Novedad.urls', namespace='Novedad')),

    url(r'^Documentos/', view=include('apps.documentos.urls', namespace='Documento')),

    url(r'^Eventos/', view=include('apps.Evento.urls', namespace='Evento')),

    url(r'^Areas/', view=include('apps.Area.urls', namespace='Area')),

    url(r'^Sedes/', view=include('apps.Sede.urls', namespace='Sede')),

    url(r'^Encuestas/', view=include('apps.Encuesta.urls', namespace='Encuesta')),
    
    #url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Encuesta/models.py
from django.db import models
from apps.core.models import TimeStampedModel
from apps.usuarios.models import Usuario
from apps.Area.models import Area
from django.db.models import Sum

class Encuesta(TimeStampedModel):
	titulo = models.CharField(max_length=60,
								verbose_name=u'Titulo',
								help_text=u'Titulo de Encuesta')

	creado_por = models.ForeignKey(Usuario)

	fecha = models.DateField(verbose_name=u'Fecha')

	area= models.ForeignKey(Area , null = True, blank=True)

	publicada = models.BooleanField(default=True, verbose_name=u'publicada')

	class Meta:
		ordering = ['-fecha']
		verbose_name = 'Encuesta'
		verbose_name_plural = 'Encuestas'

	def __str__(self):
		return self.titulo

	def get_vote_count(self):
		cant_preguntas = Pregunta.objects.filter(encuesta=self).count()
		preguntas = Pregunta.objects.filter(encuesta=self)
		contador = 0
		for p in preguntas:
			if p.get_vote_count() is not None:
				contador = contador + p.get_vote_count()
		if cant_preguntas > 0:
			return int(contador/cant_preguntas)
		else:
			return 0
	vote_count = property(fget=get_vote_count)

class Pregunta(models.Model):
	encuesta = models.ForeignKey(Encuesta)
	pregunta = models.CharField(max_length=300,
									verbose_name=u'Pregunta',)

	
	class Meta:
		verbose_name = 'Pregunta'
		verbose_name_plural = 'Preguntas'

	def __str__(self):
		return self.pregunta

	def get_vote_count(self):
		itemSum = Item.objects.filter(pregunta=self).aggregate(Sum('votos'))
		return itemSum['votos__sum']
	vote_count = property(fget=get_vote_count)

class Item(models.Model):
	pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE, null=True)
	value = models.CharField(max_length=250, verbose_name=u'opcion')
	pos = models.SmallIntegerField(default='0', verbose_name=u'position')
	votos = models.IntegerField(default='0', verbose_name=u'votos')

	class Meta:
		verbose_name ='respuesta'
		verbose_name_plural = 'respuestas'
		ordering = ['pos']

	def __str__(self):
		return u'%s' % (self.value,)
	
	def save(self, *args, **kwargs):
		self.encuesta = self.pregunta.encuesta
		super().save(*args, **kwargs)

	def get_vote_count(self):
		return Vote.objects.filter(item=self).count()
	vote_count = property(fget=get_vote_count)

class Vote(models.Model):
	encuesta = models.ForeignKey(Encuesta, verbose_name=u'encuesta')
	item = models.ForeignKey(Item, verbose_name=u'voted item')

	class Meta:
		verbose_name = 'voto'
		verbose_name_plural = 'votos'

apps/Encuesta/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from apps.usuarios.models import Usuario
from apps.core.decorators import group_required
from .models import Encuesta, Item, Vote
from apps.Area.models import Area
from django.core import serializers
from django.http import HttpResponse, Http404


class ListarEncuestas(ListView):
	model = Encuesta	
	template_name = 'encuestas/listaEncuestas.html'
	paginate_by = 10
	context_object_name = "Encuesta"
	def get_queryset(self):
		n = Encuesta.objects.all().filter(publicada=True)
		return n
	def get_context_data(self,**kwargs):
		context = super(ListarEncuestas,self).get_context_data(**kwargs)
		context['areas'] = Area.objects.all()
		paginator=context['paginator']
		pagActual=context['page_obj'].number
		cantPag=len(paginator.page_range)
		start=pagActual-2 if pagActual >= 2 else 0
		final= pagActual+2 if pagActual <= cantPag-2 else cantPag
		context['paginacion']=list(paginator.page_range)[start:final]
		return context

# Create your views here.
class Detalle_Encuesta(DetailView):
	model = Encuesta
	template_name = "encuestas/detalleEncuestas.html"
	def get_context_data(self,**kwargs):
		context = super(Detalle_Encuesta,self).get_context_data(**kwargs)
		context['areas'] = Area.objects.all()
		return context

class Resultado_Encuesta(DetailView):
	model = Encuesta
	template_name = "encuestas/resultadoEncuesta.html"
	def get_context_data(self,**kwargs):
		context = super(Resultado_Encuesta,self).get_context_data(**kwargs)
		context['areas'] = Area.objects.all()
		return context


#def vote(request, pk):
#	if request.is_ajax():
#		try:
#			encuesta = Encuesta.objects.get(pk=pk)
#		except:
#			return HttpResponse('Wrong parameters', status=400)
#
#		item_pk = request.GET.get("item", False)
#		if not item_pk:
#			return HttpResponse('Wrong parameters', status=400)
#
#		try:
#			item = Item.objects.get(pk=item_pk)
#		except:
#			return HttpResponse('Wrong parameters', status=400)
#
#		Vote.objects.create(
#			encuesta=encuesta,
#			item=item,
#		)
#
#		response = HttpResponse(status=200)
#		#set_cookie(response, encuesta.get_cookie_name(), encuesta_pk)
#
#		return response
#	return HttpResponse(status=400)

def vote(request, pk):
	encuesta = Encuesta.objects.get(pk=pk)
	if request.method == 'POST':
		item_pk = request.POST.get("item", False)

		if not item_pk:
			return HttpResponse('Wrong parameters', status=400)

		try:
			item = Item.objects.get(pk=item_pk)
		except:
			return HttpResponse('Wrong parameters', status=400)
		
		Vote.objects.create(
			encuesta=encuesta,
			item=item,
		)

		return redirect(reverse_lazy('Encuesta:encuesta_result', args=(encuesta.pk,)))

from django.http import JsonResponse

def opcion(request):
	if request.is_ajax():
		
		item_pk = request.GET.get('id_item',None)
		
		if not item_pk:
			return HttpResponse('Wrong parameters', status=400)

		try:
			item = Item.objects.get(pk=item_pk)
		except:
			return HttpResponse('Wrong parameters', status=400)
		
		item.votos=item.votos+1
		item.save()

		response = HttpResponse(status=200)

		return response
	else:
		raise Http404

templates/encuestas/detalleEncuestas.html
{% extends "base.html" %}
{% load staticfiles %}
{% load tags %}
{% block content %}
<div class="page-header sm">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<!-- Page Header Wrapper -->
				<div class="page-header-wrapper">
					<!-- Title & Sub Title -->
					<h5 class="title">Encuesta - {{object.titulo}}</h5>
				</div><!-- Page Header Wrapper -->
			</div><!-- Coloumn -->
		</div><!-- Row -->
	</div><!-- Container -->
</div>
<div role="main" class="main">
	<div class="page-default bg-grey typo-dark">
		<!-- Container -->
		<div class="container">
			<div class="row">
				<!-- Page Content -->
				<div class="col-md-9">
					<div class="row">
						<!-- Blog Column -->
						<div class="col-xs-12 blog-single">
							<div class="blog-single-wrap">
								<!-- Blog Detail Wrapper -->
								
								<div class="blog-single-details">
									
									{%csrf_token%}
									<!-- Blockquote Wrapper -->
									{% for pregunta in object.pregunta_set.all %}
										<div class="quote-wrap">
											<blockquote>		
												<p>{{pregunta.pregunta}}</p>
												<form method="POST" action="{% url 'Encuesta:ajax_vote' object.id %}" id="encuesta_form">
												{% for item in pregunta.item_set.all %}
												
													<div class="form-check" >
														  <label class="form-check-label" for="{{ item.id }}">
														    <input class="form-check-input check-input" type="radio" name="item" id="check{{ item.id }}" value="{{ item.id }}">
														    {{ item.value }}
														  </label>
														</div>
														
												{% endfor %}
												
											</blockquote>
										</div><!-- Blockquote Wrapper -->
										</form>
									{% endfor %}

									<ul class="blog-meta">
										<a class="btn" href="{% url 'Encuesta:encuesta_result' object.id %}"> Enviar Encuesta</a>
										<li><i class="fa fa-calendar-o"></i> {{object.fecha}}</li>
										{% if object.area %}
										<li><i class="fa fa-folder"></i> {{object.area}}</li>
                                		{% endif %}
										
									</ul><!-- Blog Meta -->
									<!-- Blog Description -->
						
									
									
								</div><!-- Blog Detail Wrapper -->

								
							</div><!-- Blog Wrapper -->

							
						</div><!-- Column -->
					</div><!-- Row -->
				</div><!-- Column -->
				<div class="col-md-3">
					<!-- aside -->
					<aside class="sidebar">
						
						<!-- Widget -->
						<div class="widget">
							<h5 class="widget-title">Areas<span></span></h5>
							<ul class="go-widget">
								{% for a in areas %}
									<li><a href="{% url 'Area:encuestaArea' a.id %}">{{a.nombre}}<span class="badge"></span></a></li>
								{% endfor %}
							</ul>
						</div><!-- Widget -->
					</aside><!-- aside -->	
				</div><!-- Column -->
			</div><!-- Row -->
		</div><!-- Container -->

	</div><!-- Page Default -->
</div><!-- Page Main -->
{% endblock content %}
{% block extra_js%}

<script type="text/javascript">

var vote_url = '{% url "Encuesta:ajax_vote" object.id %}';
var result_url = '{% url "Encuesta:encuesta_result" object.id %}';
document.addEventListener('DOMContentLoaded', function(){
    function showResults() {
        $.get(result_url, function(data) {
            $("#poll_container").html(data);
        });
    }
    $("#poll_send").click(function() {
        var item = $('#encuesta_form input[name=item]:checked').val();
        if (typeof item === "undefined") {
            alert("Please, select an answer");
            return false;
        }
        $.get(vote_url, {item: item}, function() {
            showResults();
        });
        return false;
    });
});


$(document).ready(function() {           
        $('.quote-wrap .check-input').click(function() {  
        	var x = $(this).attr("value");   
        	 $("#check"+x).attr('checked', true);
        	console.log(x);                   
                $.ajax({ 
                    data:{'id_item':x}, 
                    url : "{% url 'Encuesta:seleccionOpcion' %}",
                    type: 'get',
                	cache: false,
                    success: function(data) { 
                        console.log(data);
                    },
                    fail: function (data) {
                      console.log("Error: ");
                  }
                }); 
                
            

        }); 
    });
</script>

{% endblock extra_js%}

templates/encuestas/listaEncuestas.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}



<div class="page-header sm">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<!-- Page Header Wrapper -->
				<div class="page-header-wrapper">
					<!-- Title & Sub Title -->
					<h5 class="title">Encuestas</h5>
				</div><!-- Page Header Wrapper -->
			</div><!-- Coloumn -->
		</div><!-- Row -->
	</div><!-- Container -->
</div>
<div role="main" class="main">
	<div class="page-default bg-grey typo-dark">
		<!-- Container -->
		<div class="container">
			<div class="row">
				<!-- Page Content -->
				<div class="col-md-9">
					{% if Encuesta %}
					<ul class="row" >
						{% for e in Encuesta%}
						<li class="col-xs-12 blog-list-wrap" >
					<!-- Blog Wrapper -->
						<div class="row blog-wrap">
							<!-- Blog Detail Wrapper -->
							<div class="col-sm-12">
								<div class="blog-details">
									<h4>{{e.titulo}}</h4>
									<ul class="blog-meta" >
										<li><i class="fa fa-calendar-o"></i>{{e.fecha}}</li>
									</ul><!-- Blog Meta -->
									<p>{{e.pregunta}}</p>
									<a class="btn" href="{% url 'Encuesta:detalle_encuesta' e.id %}">Realizar encuesta</a>
								<a class="btn" href="{% url 'Encuesta:encuesta_result' e.id %}">Ver Resultados</a>
								</div><!-- Blog Detail Wrapper -->
							</div><!-- Blog Detail Column -->
						</div><!-- Blog Wrapper -->
					<!-- Divider -->
					<hr class="md">
				</li><!-- Column -->

						{%endfor%}
						{% include 'pagination/pagination.html' %}
					</ul><!-- Row -->
					{% else%}
					<div role="alert" class="alert alert-danger"> 
						<strong>No hay encuestas cargadas</strong> 
					</div>
					{%endif%}
				</div><!-- Column -->

				<div class="col-md-3">
					<!-- aside -->
					<aside class="sidebar">
						
						<!-- Widget -->
						<div class="widget">
							<h5 class="widget-title">Areas<span></span></h5>
							<ul class="go-widget">
								{% for a in areas %}
								<li><a href="{% url 'Area:encuestaArea' a.id %}">{{a.nombre}}<span class="badge"></span></a></li>
								{% endfor %}
							</ul>
						</div><!-- Widget -->
					</aside><!-- aside -->	
				</div><!-- Column -->
			</div><!-- Row -->	
		</div><!-- Container -->
	</div><!-- Page Default -->
</div><!-- Page Main -->

{% endblock content %}

{% block extra_js%}

<script type="text/javascript">

</script>

{% endblock extra_js%}

templates/encuestas/resultadoEncuesta.html
{% extends "base.html" %}
{% load staticfiles %}
{% load tags %}
{% load encuesta_tags %}
{% block content %}
<div class="page-header sm">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<!-- Page Header Wrapper -->
				<div class="page-header-wrapper">
					<!-- Title & Sub Title -->
					<h5 class="title">Encuestas - {{object.titulo}}</h5>
				</div><!-- Page Header Wrapper -->
			</div><!-- Coloumn -->
		</div><!-- Row -->
	</div><!-- Container -->
</div>
<div role="main" class="main">
	<div class="page-default bg-grey typo-dark">
		<!-- Container -->
		<div class="container">
			<div class="row">
				<!-- Page Content -->
				<div class="col-md-9">
					<div class="row">
						<!-- Blog Column -->
						<div class="col-xs-12 blog-single">
							<div class="blog-single-wrap">
								<!-- Blog Detail Wrapper -->
								<div class="blog-single-details">
								{% for pregunta in object.pregunta_set.all %}
								<div class="quote-wrap">
									<blockquote>	
										<p>{{pregunta.pregunta}}</p>
										
										<!-- Blog Description -->
										{% for item in pregunta.item_set.all %}
											<h6 class="progress-tille">{{ item.value }}:</h6>
												<div class="progress bg-verydark" data-height="5" style="line-height: 5px; height: 5px;">
													<div data-percentage="{% percentage pregunta item %}" aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" class="progress-bar" style="width: {% percentage pregunta item %}%;">
														<span class="progress-label">{% percentage pregunta item %}%</span>
													</div>
											</div><!-- Progress Bar -->
										{% endfor %}
										<br>
										</blockquote>
									</div><!-- Blockquote Wrapper -->
									{% endfor %}
									<ul class="blog-meta">
											<li><i class="fa fa-calendar-o"></i> {{object.fecha}}</li>
											{% if object.area %}
											<li><i class="fa fa-folder"></i> {{object.area}}</li>
	                                		{% endif %}
											<li><p>Total de votos :<b>{{ object.get_vote_count }}</b></p></li>
										</ul><!-- Blog Meta -->
								</div><!-- Blog Detail Wrapper -->
							</div><!-- Blog Wrapper -->

							
						</div><!-- Column -->
					</div><!-- Row -->
				</div><!-- Column -->
				<div class="col-md-3">
					<!-- aside -->
					<aside class="sidebar">
						
						<!-- Widget -->
						<div class="widget">
							<h5 class="widget-title">Areas<span></span></h5>
							<ul class="go-widget">
								{% for a in areas %}
									<li><a href="{% url 'Area:encuestaArea' a.id %}">{{a.nombre}}<span class="badge"></span></a></li>
								{% endfor %}
							</ul>
						</div><!-- Widget -->
					</aside><!-- aside -->	
				</div><!-- Column -->
			</div><!-- Row -->
		</div><!-- Container -->

	</div><!-- Page Default -->
</div><!-- Page Main -->
{% endblock content %}
{% block extra_js%}

{% endblock extra_js%}