apps/Encuesta/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^encuestas/', views.ListarEncuestas.as_view(), name='listarEncuestas'),
    url(r'^poll/(?P<pk>[0-9]+)/', views.Detalle_Encuesta.as_view(), name='detalle_encuesta'),
	url(r'^result/(?P<pk>[0-9]+)/', views.Resultado_Encuesta.as_view(), name='encuesta_result'),
	url(r'^vote/(?P<pk>[0-9]+)/', views.vote, name='ajax_vote'),
	url(r'^opcion/$', views.opcion, name='seleccionOpcion'),


]

apps/Evento/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^eventos/', views.ListarEventos.as_view(), name='listarEventos'),
    url(r'^detalleEvento/(?P<pk>[0-9]+)/', views.Detalle_Evento.as_view(), name='detalle_evento'),

]

apps/documentos/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^documentos/', views.ListarDocumentos.as_view(), name='listarDocumentos'),

]

unitan/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from .views import Start, institucional
from apps.Novedad import views

from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^institucional/', institucional, name='institucional'),

    url(r'^$', views.ListarNovedades.as_view(), name='listarNovedades'),

    url(r'^Novedades/', view=include('apps.Novedad.urls', namespace='Novedad')),

    url(r'^Documentos/', view=include('apps.documentos.urls', namespace='Documento')),

    url(r'^Eventos/', view=include('apps.Evento.urls', namespace='Evento')),

    url(r'^Areas/', view=include('apps.Area.urls', namespace='Area')),

    url(r'^Sedes/', view=include('apps.Sede.urls', namespace='Sede')),

    url(r'^Encuestas/', view=include('apps.Encuesta.urls', namespace='Encuesta')),
    
    #url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Encuesta/models.py
from django.db import models
from apps.core.models import TimeStampedModel
from apps.usuarios.models import Usuario
from apps.Area.models import Area
from django.db.models import Sum

class Encuesta(TimeStampedModel):
	titulo = models.CharField(max_length=60,
								verbose_name=u'Titulo',
								help_text=u'Titulo de Encuesta')

	creado_por = models.ForeignKey(Usuario)

	fecha = models.DateField(verbose_name=u'Fecha')

	area= models.ForeignKey(Area , null = True, blank=True)

	publicada = models.BooleanField(default=True, verbose_name=u'publicada')

	class Meta:
		ordering = ['-fecha']
		verbose_name = 'Encuesta'
		verbose_name_plural = 'Encuestas'

	def __str__(self):
		return self.titulo

	def get_vote_count(self):
		cant_preguntas = Pregunta.objects.filter(encuesta=self).count()
		preguntas = Pregunta.objects.filter(encuesta=self)
		contador = 0
		for p in preguntas:
			if p.get_vote_count() is not None:
				contador = contador + p.get_vote_count()
		if cant_preguntas > 0:
			return int(contador/cant_preguntas)
		else:
			return 0
	vote_count = property(fget=get_vote_count)

class Pregunta(models.Model):
	encuesta = models.ForeignKey(Encuesta)
	pregunta = models.CharField(max_length=300,
									verbose_name=u'Pregunta',)

	
	class Meta:
		verbose_name = 'Pregunta'
		verbose_name_plural = 'Preguntas'

	def __str__(self):
		return self.pregunta

	def get_vote_count(self):
		itemSum = Item.objects.filter(pregunta=self).aggregate(Sum('votos'))
		return itemSum['votos__sum']
	vote_count = property(fget=get_vote_count)

class Item(models.Model):
	pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE, null=True)
	value = models.CharField(max_length=250, verbose_name=u'opcion')
	pos = models.SmallIntegerField(default='0', verbose_name=u'position')
	votos = models.IntegerField(default='0', verbose_name=u'votos')

	class Meta:
		verbose_name ='respuesta'
		verbose_name_plural = 'respuestas'
		ordering = ['pos']

	def __str__(self):
		return u'%s' % (self.value,)
	
	def save(self, *args, **kwargs):
		self.encuesta = self.pregunta.encuesta
		super().save(*args, **kwargs)

	def get_vote_count(self):
		return Vote.objects.filter(item=self).count()
	vote_count = property(fget=get_vote_count)

class Vote(models.Model):
	encuesta = models.ForeignKey(Encuesta, verbose_name=u'encuesta')
	item = models.ForeignKey(Item, verbose_name=u'voted item')

	class Meta:
		verbose_name = 'voto'
		verbose_name_plural = 'votos'

apps/Encuesta/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from apps.usuarios.models import Usuario
from apps.core.decorators import group_required
from .models import Encuesta, Item, Vote
from apps.Area.models import Area
from django.core import serializers
from django.http import HttpResponse, Http404


class ListarEncuestas(ListView):
	model = Encuesta	
	template_name = 'encuestas/listaEncuestas.html'
	paginate_by = 10
	context_object_name = "Encuesta"
	def get_queryset(self):
		n = Encuesta.objects.all().filter(publicada=True)
		return n
	def get_context_data(self,**kwargs):
		context = super(ListarEncuestas,self).get_context_data(**kwargs)
		context['areas'] = Area.objects.all()
		paginator=context['paginator']
		pagActual=context['page_obj'].number
		cantPag=len(paginator.page_range)
		start=pagActual-2 if pagActual >= 2 else 0
		final= pagActual+2 if pagActual <= cantPag-2 else cantPag
		context['paginacion']=list(paginator.page_range)[start:final]
		return context

# Create your views here.
class Detalle_Encuesta(DetailView):
	model = Encuesta
	template_name = "encuestas/detalleEncuestas.html"
	def get_context_data(self,**kwargs):
		context = super(Detalle_Encuesta,self).get_context_data(**kwargs)
		context['areas'] = Area.objects.all()
		return context

class Resultado_Encuesta(DetailView):
	model = Encuesta
	template_name = "encuestas/resultadoEncuesta.html"
	def get_context_data(self,**kwargs):
		context = super(Resultado_Encuesta,self).get_context_data(**kwargs)
		context['areas'] = Area.objects.all()
		return context


#def vote(request, pk):
#	if request.is_ajax():
#		try:
#			encuesta = Encuesta.objects.get(pk=pk)
#		except:
#			return HttpResponse('Wrong parameters', status=400)
#
#		item_pk = request.GET.get("item", False)
#		if not item_pk:
#			return HttpResponse('Wrong parameters', status=400)
#
#		try:
#			item = Item.objects.get(pk=item_pk)
#		except:
#			return HttpResponse('Wrong parameters', status=400)
#
#		Vote.objects.create(
#			encuesta=encuesta,
#			item=item,
#		)
#
#		response = HttpResponse(status=200)
#		#set_cookie(response, encuesta.get_cookie_name(), encuesta_pk)
#
#		return response
#	return HttpResponse(status=400)

def vote(request, pk):
	encuesta = Encuesta.objects.get(pk=pk)
	if request.method == 'POST':
		item_pk = request.POST.get("item", False)

		if not item_pk:
			return HttpResponse('Wrong parameters', status=400)

		try:
			item = Item.objects.get(pk=item_pk)
		except:
			return HttpResponse('Wrong parameters', status=400)
		
		Vote.objects.create(
			encuesta=encuesta,
			item=item,
		)

		return redirect(reverse_lazy('Encuesta:encuesta_result', args=(encuesta.pk,)))

from django.http import JsonResponse

def opcion(request):
	if request.is_ajax():
		
		item_pk = request.GET.get('id_item',None)
		
		if not item_pk:
			return HttpResponse('Wrong parameters', status=400)

		try:
			item = Item.objects.get(pk=item_pk)
		except:
			return HttpResponse('Wrong parameters', status=400)
		
		item.votos=item.votos+1
		item.save()

		response = HttpResponse(status=200)

		return response
	else:
		raise Http404

templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
	<head>
		<!-- Basic -->
		<meta charset="utf-8">
		<title>
        {% block subtitle_content %}
            {% block subtitle %}{% endblock subtitle%}
            {% ifnotequal request.path '/' %} — {% endifnotequal %}
        {% endblock subtitle_content %}
        {% block title %}Unitan Interno{% endblock title %}
    </title>
		<meta name="keywords" content="Universh - Material Education, Events, News, Learning Centre & Kid School MultiPurpose HTML5 Template" />
		<meta name="description" content="Universh - Material Education, Events, News, Learning Centre & Kid School MultiPurpose HTML5 Template">
		<meta name="author" content="glorythemes.in">
		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- Favicon -->
        <link rel="shortcut icon" href="{% static 'images/default/favicon2.png'%}">
		<!-- Web Fonts  -->
		<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' 
		rel='stylesheet' type='text/css'>

		<!-- Lib CSS -->
		<link rel="stylesheet" href="{% static 'css/lib/bootstrap.min.css'%}" rel="stylesheet" media="screen,projection">
		<link rel="stylesheet" href="{% static 'css/lib/animate.min.css'%}" rel="stylesheet" media="screen,projection">
		<link rel="stylesheet" href="{% static 'css/lib/font-awesome.min.css'%}" rel="stylesheet" media="screen,projection">
		<link rel="stylesheet" href="{% static 'css/lib/univershicon.css'%}" rel="stylesheet" media="screen,projection">
		<link rel="stylesheet" href="{% static 'css/lib/owl.carousel.css'%}" rel="stylesheet" media="screen,projection">
		<link rel="stylesheet" href="{% static 'css/lib/prettyPhoto.css'%}" rel="stylesheet" media="screen,projection">
		<link rel="stylesheet" href="{% static 'css/lib/menu.css'%}" rel="stylesheet" media="screen,projection">
		<link rel="stylesheet" href="{% static 'css/lib/timeline.cs'%}" rel="stylesheet" media="screen,projection">
		
		<!-- Theme CSS -->
		<link rel="stylesheet" href="{% static 'css/theme.css'%}">
		<link rel="stylesheet" href="{% static 'css/theme-responsive.css'%}">
		
		<!--[if IE]>
			<link rel="stylesheet" href="css/ie.css">
		<![endif]-->
		
		<!-- Skins CSS -->
		<link rel="stylesheet" href="{% static 'css/skins/default.css'%}">
		
		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="{% static 'css/custom.css'%}">
	</head>
<body>

<!-- Page Loader -->
<div id="pageloader">
	<div class="loader-inner">
		<img src="{% static 'images/default/preloader-color.gif'%}">
	</div>
</div><!-- Page Loader -->

<!-- Back to top -->
<a href="#0" class="cd-top">Top</a>

<!-- End Theme Panel Switcher -->

	
<!-- Header Begins -->	
<header id="header" class="default-header colored flat-menu">
	<div class="container">
		<div class="logo">
			<a  href="{% url 'Novedad:listarNovedades' %}">
				 <img alt="Universh" width="150" height="56" data-sticky-width="150" data-sticky-height="28" src="{% static 'images/unitan1.jpg'%}">
			</a>
		</div>
		<button class="btn btn-responsive-nav btn-inverse" data-toggle="collapse" data-target=".nav-main-collapse">
			<i class="fa fa-bars"></i>
		</button>
	</div>
	<div class="navbar-collapse nav-main-collapse collapse">
		<div class="container">
			<nav class="nav-main mega-menu">
				<ul class="nav nav-pills nav-main" id="mainMenu">
					<li class="dropdown">
						<a class="dropdown-toggle" href="{% url 'Novedad:listarNovedades' %}">
							Novedades
						</a>
					</li>

					<li class="dropdown">
						<a class="dropdown-toggle" href="{% url 'Documento:listarDocumentos' %}">
							Documentos
						</a>
					</li>
					
					<li class="dropdown">
						<a class="dropdown-toggle" href="{% url 'Evento:listarEventos' %}">
							Eventos
						</a>
					</li>
					<li class="dropdown">
						<a class="dropdown-toggle" href="{% url 'Encuesta:listarEncuestas' %}">
							Encuestas
						</a>
					</li>
					<li class="dropdown">
						<a class="dropdown-toggle" href="{% url 'institucional' %}">
							Institucional
						</a>
					</li>
				</ul>
			</nav>
		</div>
	</div>
</header><!-- Header Ends -->
		
<!-- //////////////////////////////////////////////////////////////////////////// -->

      <!-- START CONTENT -->
       {% block content %}
          
      {% endblock content %}
      <!-- END CONTENT -->

      <!-- //////////////////////////////////////////////////////////////////////////// -->
      <!-- START RIGHT SIDEBAR NAV-->

<!-- Footer -->
<footer id="footer" class="footer-3">
	<!-- Main Footer -->
	<div class="main-footer widgets-dark typo-light">
		<div class="container">
			<!-- Footer top -->
			<div class="footer-top">
				<div class="row">
					<!-- Footer top logo -->
					<div class="col-sm-2">
						<a href="index.html" class="logo">
							<img width="211" height="40" alt="Universh Education HTML5 Website Template" class="img-responsive" src="{% static 'images/normas2.jpg'%}">
							<p class="slogan">Comunicacion interna</p>
						</a>
					</div><!-- Footer top logo -->
					
					<!-- Footer top left Content -->
					<div class="col-sm-10 footer-top-right text-right">
						<!-- Widget -->
						<div class="widget no-box">
							<!-- Counter
							<div class="count-widget inline">
								<span class="count-number" data-count="250"><span class="counter"></span></span>
								<span class="title">Visitas</span>
								
							</div> Counter -->
							<!-- Counter -->
							<div class="count-widget inline">
								<span class="count-number" data-count="1923"><span class="counter"></span></span>
								<span class="title">Visitas</span>
							</div><!-- Counter -->
							<!-- Counter -->
							<div class="count-widget inline">
								<span class="count-number" data-count="3"><span class="counter"></span></span>
								<span class="title">Sedes</span>
							</div><!-- Counter -->
							
							
						</div><!-- Widget -->
					</div><!-- Count -->
					
				</div><!-- Footer top row -->
			</div><!-- Footer top -->
		</div><!-- Container -->		
	</div><!-- Main Footer -->
	
	<!-- Footer Copyright -->
	<div class="footer-copyright">
		<div class="container">
			<div class="row">
				<!-- Copy Right Content -->
				<div class="col-md-6">
					<p>&copy;Todos los derechos reservados. | By <a href="https://www.facebook.com/Saint-Web-2247623195490756/?modal=admin_todo_tour" title="glorythemes">BlasCG.SaintWeb</a></p>
				</div><!-- Copy Right Content -->
				<!-- Copy Right Content -->
				<div class="col-md-6">
					<nav class="sm-menu">
						<ul>
							<li><a href="http://www.unitan.net/">Sitio web</a></li>
						</ul>
					</nav><!-- Nav -->
				</div><!-- Copy Right Content -->
			</div><!-- Footer Copyright -->
		</div><!-- Footer Copyright container -->
	</div><!-- Footer Copyright -->
</footer>
<!-- Footer -->

<!-- library -->
<script src="{% static 'js/lib/jquery.js' %}"></script>
<script src="{% static 'js/lib/bootstrap.min.js' %}"></script>
<script src="{% static 'js/lib/bootstrapValidator.min.js' %}"></script>
<script src="{% static 'js/lib/jquery.appear.js' %}"></script>
<script src="{% static 'js/lib/jquery.easing.min.js' %}"></script>
<script src="{% static 'js/lib/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/lib/countdown.js' %}"></script>
<script src="{% static 'js/lib/counter.js' %}"></script>
<script src="{% static 'js/lib/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'js/lib/jquery.easypiechart.min.js' %}"></script>
<script src="{% static 'js/lib/jquery.mb.YTPlayer.min.js' %}"></script>
<script src="{% static 'js/lib/jquery.prettyPhoto.js' %}"></script>
<script src="{% static 'js/lib/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/lib/menu.js"></script>
<script src="{% static 'hitcount/hitcount-jquery.js' %}"></script>

<script src="{% static 'js/lib/modernizr.js' %}"></script>
<!-- Theme Base, Components and Settings -->
<script src="{% static 'js/theme.js' %}"></script>

<!-- Theme Custom -->
<script src="{% static 'js/custom.js' %}"></script>

<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<!-- or -->
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>

{% block extra_js%}
    {% endblock extra_js%}

</body>
</html>

templates/encuestas.html
{% load poll_tags %}
...
{% poll %}

templates/institucional.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<section class="relative bg-light typo-dark parallax-bg bg-cover overlay white sm" data-background="{% static 'images/fuego.jpg'%}" data-stellar-background-ratio="0.5" style="background-image: url(&quot;{% static 'images/fuego.jpg'%}&quot;); background-position: 0px -50.5px;">
		<div class="container parent-has-overlay">
			<div class="row">
				<div class="col-md-12">
					<div class="title-container margin-none text-left">
						<div class="title-wrap">
							<h2 class="title">Institucional</h2>
							<span class="separator dot-separator">...</span>
						</div>							
					</div><!-- Name -->
				</div><!-- Column -->
			</div><!-- Row -->
		</div><!-- Container -->
	</section>

<div role="main" class="main">
	<div class="page-default bg-grey typo-dark">
		<!-- Container -->
		<div class="container">
			<div class="col-sm-12">
					<!-- Gallery Single Details -->
					<div class="gallery-single-detail">
					<div class="row"></div>
						<div class="col-sm-6">
						<h4>Política de Calidad </h4>
						
						<!-- Description -->
						<p>UNITAN SAICA lidera desde hace más de 110 años la industria del tanino vegetal y sus derivados. Quienes integramos UNITAN tenemos el compromiso de:</p>
						
						<p>• Conseguir y mantener la confianza de nuestros clientes.</p>

						<p>• Afianzar la imagen, prestigio y calidad de nuestros productos y servicios.</p>
						<p>• Investigar y desarrollar nuevas aplicaciones.</p>
						<p>• Lograr el crecimiento sostenido de nuestra empresa.</p>
						<p>• Contribuir al desarrollo regional y de nuestro país.</p>
						<br>
						<h5><b>Por ello, nuestro esfuerzo debe enfocarse en:</b></h5>
						
						<!-- Description -->
						<h5><b>GENERAR Y SUSTENTAR RELACIONES DE LARGO PLAZO:</b></h5>
						<p>• Acrecentando en todos nuestros usuarios la confianza de que nuestros productos y servicios cumplen cabalmente con las especificaciones acordadas.</p>
						<p>• Estando atentos a nuevas inquietudes y requerimientos para ofrecer  productos innovadores que aporten soluciones viables y ayuden a nuestros clientes a ser más competitivos.</p>
						<p>• Afianzando nuestra red comercial a fin de brindar mejor servicio y mayor satisfacción a nuestros clientes.</p>

						<h5><b>REALIZAR UN TRABAJO DEL QUE NOS SINTAMOS ORGULLOSOS :</b></h5>
						<p>• Utilizando los métodos de prevención, planificación, mejora continua y capacitación como herramientas de superación.</p>
						<p>•  Fomentando la conciencia por la responsabilidad en cada actividad.</p>
						<p>• Manteniendo a toda la organización involucrada en el cumplimiento de esta Política.</p>
						<p>• Haciendo de la Calidad, la Seguridad y el cumplimiento de las Normas Ambientales las bases de nuestra gestión.</p>
						<p>De esta forma seguiremos construyendo UNA TRADICIÓN CON FUTURO.</p>

						</div>
						</div>
					</div><!-- Gallery Single Details -->
				</div>
		</div><!-- Container -->
	</div><!-- Page Default -->
</div><!-- Page Main -->

{% endblock content %}

{% block extra_js%}

<script type="text/javascript">

</script>

{% endblock extra_js%}